name: tech_challenge_3
description: "Bytebank Tech Challenge 3"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  shared_preferences:
  file_selector: ^1.0.3
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cloud_firestore: ^5.6.8
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  firebase_storage:
  image_picker:
  fl_chart:
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
