name: tech_challenge_3
description: "Bytebank Tech Challenge 3"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  shared_preferences:
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
