// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhI_p7htEq76o4B5slE81FG7RUsPlyeGo',
    appId: '1:858480286980:web:d04a214bcf6966e6a48451',
    messagingSenderId: '858480286980',
    projectId: 'tech-challenge-3-34817',
    authDomain: 'tech-challenge-3-34817.firebaseapp.com',
    storageBucket: 'tech-challenge-3-34817.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TZoDTE3mkmKgFw2cXN9kIZC_-QwX08Q',
    appId: '1:858480286980:android:0d9c293523469755a48451',
    messagingSenderId: '858480286980',
    projectId: 'tech-challenge-3-34817',
    storageBucket: 'tech-challenge-3-34817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPunbhkMamjTBnGYYYuvcFq-XwyCartoY',
    appId: '1:858480286980:ios:fc9b463dbee7f053a48451',
    messagingSenderId: '858480286980',
    projectId: 'tech-challenge-3-34817',
    storageBucket: 'tech-challenge-3-34817.firebasestorage.app',
    iosBundleId: 'com.example.techChallenge3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPunbhkMamjTBnGYYYuvcFq-XwyCartoY',
    appId: '1:858480286980:ios:fc9b463dbee7f053a48451',
    messagingSenderId: '858480286980',
    projectId: 'tech-challenge-3-34817',
    storageBucket: 'tech-challenge-3-34817.firebasestorage.app',
    iosBundleId: 'com.example.techChallenge3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhI_p7htEq76o4B5slE81FG7RUsPlyeGo',
    appId: '1:858480286980:web:bde388aaf930fde0a48451',
    messagingSenderId: '858480286980',
    projectId: 'tech-challenge-3-34817',
    authDomain: 'tech-challenge-3-34817.firebaseapp.com',
    storageBucket: 'tech-challenge-3-34817.firebasestorage.app',
  );
}
